### ISSUE TITLE
QUESTION : Why use a btrfs blank snapshot instead of tmpfs ?

### ISSUE THREAD

**Issue by Nandicre2** [Misterio77/nix-config#11]
Just asking, because i tought that snapshoting was bad for the SSD longetivity.

**Comment by Misterio77** [comment]
Hello!

I'm actually considering moving back to ext4+tmpfs, because of simplicity mostly.

Btrfs does have a couple of goodies that might make it worth using:
- Snapshots: useful to have lightweight "backups" (for human error situation, that is) for your data
- Transparent compression: shaves off about 20-30% storage with negligible performance impact
- Subvolumes: you can have logical volumes within the same physical partition, making it pretty painless to organize stuff into different mountpoints if needed

**Comment by Nandicre2** [comment]
I'm actually considering using

**Comment by Nandicre2** [comment]
(sorry for the open and close, was answering from my phone)

I'm actually considering using both : tmpfs as root and everything else on btrfs. I found [this blog post](https://cnx.srht.site/blog/butter/) and I think I'll go this way

**Comment by luxus** [comment]
would https://github.com/nix-community/disko not help with the "its complicated" part? didn't checked it out yet.

**Comment by Nandicre2** [comment]
> would https://github.com/nix-community/disko not help with the "its complicated" part? didn't checked it out yet.

Didn't checked it out either. I've seen it mentioned on the forum but i don't want to mess with it now. Maybe later

**Comment by Misterio77** [comment]
> would https://github.com/nix-community/disko not help with the "its complicated" part? didn't checked it out yet.

Disko is pretty cool. Moving my setup to it is definitively on my todo-list.

**Comment by omernaveedxyz** [comment]
My issue with tmpfs is that you have to specify a size for the tmpfs root or be limited based on your RAM. Tmpfs defaults to half your system RAM (I believe). Some guides set tmpfs to 2GiB (example), but that means that you can only have up to 2GiB of files on root outside of the ones you have persisted or on a separate partition. Btrfs' logical volumes + snapshots avoid this by having automatically resizing subvolumes so I never have to think about it.

**Comment by NerdHusky** [comment]
> (sorry for the open and close, was answering from my phone)
> 
> I'm actually considering using both : tmpfs as root and everything else on btrfs. I found [this blog post](https://cnx.srht.site/blog/butter/) and I think I'll go this way

Nice post! Wish I'd found it sooner!
No really, I went with btrfs because it's really cool, I could make a raid with it without LVM it has compression (really 0 performance decrease with raid0) and...COW! ;)
Plus yeah some snapshotting for backup purposes do no harm I guess! ;) not to /nix of course, but /home and maybe /persist (especially when I'll wipe out even home at boot - the original post doesn't but I'll go for it once my home-manager configuration is really solid).

**Comment by NerdHusky** [comment]
> My issue with tmpfs is that you have to specify a size for the tmpfs root or be limited based on your RAM. Tmpfs defaults to half your system RAM (I believe). Some guides set tmpfs to 2GiB (example), but that means that you can only have up to 2GiB of files on root outside of the files you have persisted on a separate partition. Btrfs' logical volumes avoid this by having automatically resizing subvolumes so I never have to think about the size of individual subvolumes.

That I didn't know and if it's true it really sucks because I'm already using zram xD.

**Comment by threddast** [comment]
I have been using tmpfs for a while, and to be honest it has its quirks, see for example https://github.com/nix-community/impermanence/issues/124 . This issue is not present when root is on btrfs.

**Comment by musjj** [comment]
How's the situation with tmpfs recently? Looking into impermanence, but ZFS/Btrfs is too much for me.
