### ISSUE TITLE
have anyone used nix-generator with this config?

### ISSUE THREAD

**Issue by luxus** [Misterio77/nix-config#15]
hello, i need to generate some images for virtualisation and want to generate the images with the config, does anyone use it?

**Comment by sjcobb2022** [comment]
Hey @luxus was playing around and i have this config which currently works! 
```nix
#flake.nix
packages =
    forEachPkgs
      (
        pkgs:
          (import ./pkgs {inherit pkgs;})
          // {
            install-iso = inputs.nixos-generators.nixosGenerate {
              system = "${pkgs.system}";
              format = "install-iso";
            };
          }
      );
```
      
 I augment the main package to include an install-iso generator.
 
 If you try to add this as a regular package, there are infinite recursion issues. This is because there is an overlay (below) that brings custom packages into scope, which means that the installer iso package references itself.
 
 ```nix
   # This one brings our custom packages from the 'pkgs' directory
  additions = final: _prev: import ../pkgs {pkgs = final;};
 ```
